strictness: low

#test-warnings: true
#doc-warnings: true

ignore-patterns:
    - test_*

ignore-paths:
    - default_scripts

dodgy:
    # Looks at Python code to search for things which look "dodgy"
    # such as passwords or git conflict artifacts
    run: true

mccabe:
    # complexity checking.
    run: true

pep257:
    # docstring checking
    run: false
    disable:
        - D105 # Missing ocstring in magic Method
        - D203 # 1 Blank before Class Docstring
        - D213 # Multiline Docstring should start on second line

pep8:
    # style checking
    run: true
    disable:
        - E741 # Ambigous Variable Name I l O  I really like l. Use better Fonts 11

pyflakes:
    run: true

pylint:
    # static analysis and then some
    run: true
    options:
        dummy-variables-rgx: '_$|__$|dummy'
        ignored-classes: pytest
    disable:
        - relative-beyond-top-level
        - import-outside-toplevel
        - inconsistent-return-statements
